# Generated by Django 5.0.3 on 2024-08-23 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('idBarbearia', models.AutoField(primary_key=True, serialize=False)),
                ('hrAbertura', models.CharField(blank=True, max_length=255, null=True)),
                ('hrFechamento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('idBarbeiro', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBarbeiro', models.CharField(max_length=255)),
                ('telefoneBarbeiro', models.CharField(blank=True, max_length=255, null=True)),
                ('fotoBarbeiro', models.ImageField(blank=True, upload_to='barbeiro/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCliente', models.CharField(max_length=255)),
                ('telefoneCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('emailCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('sexoCliente', models.CharField(blank=True, max_length=1, null=True)),
                ('barbeiroPreferido', models.CharField(blank=True, max_length=255, null=True)),
                ('fotoCliente', models.ImageField(upload_to='cliente/')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Agenda')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.CharField(choices=[('08:00-09:00', '08:00 às 09:00'), ('09:00-10:00', '09:00 às 10:00'), ('10:00-11:00', '10:00 às 11:00'), ('13:00-14:00', '13:00 às 14:00'), ('14:00-15:00', '14:00 às 15:00'), ('15:00-16:00', '15:00 às 16:00'), ('16:00-17:00', '16:00 às 17:00'), ('17:00-18:00', '17:00 às 18:00'), ('18:00-19:00', '18:00 às 19:00')], max_length=11, verbose_name='Horário')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barbearia', verbose_name='Barbearia')),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barbeiro', verbose_name='Barbeiro')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agenda', verbose_name='Agenda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalha',
            fields=[
                ('idBarbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.barbeiro')),
                ('idBarbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barbearia')),
            ],
        ),
    ]
