# Generated by Django 5.0.3 on 2024-03-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('idBarbeiro', models.AutoField(primary_key=True, serialize=False)),
                ('NomeBarbeiro', models.CharField(max_length=255)),
                ('telefoneBarbeiro', models.CharField(blank=True, max_length=255, null=True)),
                ('fotoBarbeiro', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
