# Generated by Django 5.0.3 on 2024-03-15 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('idBarbearia', models.AutoField(primary_key=True, serialize=False)),
                ('hrAbertura', models.DateField(null=True)),
                ('hrFechamento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCliente', models.CharField(max_length=255)),
                ('telefoneCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('emailCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('sexoCliente', models.CharField(blank=True, max_length=1, null=True)),
                ('barbeiroPreferido', models.CharField(blank=True, max_length=255, null=True)),
                ('fotoCliente', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('dataCompleta', models.DateField()),
                ('idAgendamento', models.AutoField(primary_key=True, serialize=False)),
                ('idBarbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barbeiro')),
                ('idBarbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barbearia')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalha',
            fields=[
                ('idBarbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.barbeiro')),
                ('idBarbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.barbearia')),
            ],
        ),
    ]
