# Generated by Django 5.0.4 on 2024-04-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_barbearia_hrabertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='hrAbertura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='hrFechamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
